/**
 * LatAm Music Presets Library
 * Bilingual (English + Spanish) presets with prompt templates for common music styles.
 * Presets are culturally aware and designed for original composition, not artist imitation.
 */

export const LATAM_MUSIC_PRESETS = [
  {
    id: 'reggaeton-cinematic',
    nameEn: 'Reggaetón Cinematic',
    nameEs: 'Reggaetón Cinemático',
    descriptionEn: 'Modern reggaetón with cinematic strings and rich production',
    descriptionEs: 'Reggaetón moderno con cuerdas cinemáticas y producción rica',
    locale: ['es-MX', 'es-CO', 'es-US'],
    genre: 'reggaetón',
    mood: 'energetic',
    bpmMin: 90,
    bpmMax: 100,
    defaultBpm: 96,
    key: 'Em',
    instruments: ['drums', 'bass', 'strings', 'synth', 'perc'],
    styleTags: ['urban', 'modern', '2024', 'cinematic'],
    promptTemplateEn: 'Cinematic reggaetón track with orchestral strings, modern production, driving beat, urban vibe',
    promptTemplateEs: 'Pista de reggaetón cinemático con cuerdas orquestales, producción moderna, ritmo envolvente, vibra urbana',
    negativePrompt: 'harsh, lo-fi, acoustic, voice imitation, artist name reference',
    culturalNotes: 'Reggaetón evolved from Jamaican dancehall and Puerto Rican roots; modern remixes often blend orchestral elements',
    suggestedVideoStyle: 'urban-nightlife, street-art, modern-city',
    suggestedCameraPreset: 'dynamic-tracking, wide-landscape',
  },
  {
    id: 'cumbia-pop',
    nameEn: 'Cumbia Pop',
    nameEs: 'Cumbia Pop',
    descriptionEn: 'Contemporary cumbia fusion with pop sensibilities and modern production',
    descriptionEs: 'Fusión contemporánea de cumbia con sensibilidad pop y producción moderna',
    locale: ['es-CO', 'es-PE', 'es-EC'],
    genre: 'cumbia',
    mood: 'celebratory',
    bpmMin: 90,
    bpmMax: 105,
    defaultBpm: 98,
    key: 'G',
    instruments: ['percussion', 'horns', 'synth', 'bass', 'drums'],
    styleTags: ['tropical', 'celebratory', 'dance', 'modern'],
    promptTemplateEn: 'Contemporary cumbia with bright brass section, synth layers, dancing percussion, pop-forward production',
    promptTemplateEs: 'Cumbia contemporánea con sección de metales brillantes, capas de sintetizadores, percusión bailarina, producción orientada al pop',
    negativePrompt: 'acoustic guitar only, traditional acoustic, voice imitation',
    culturalNotes: 'Cumbia is the national rhythm of Colombia and Peru; combines African, Spanish, and Indigenous influences',
    suggestedVideoStyle: 'celebration, carnival, street-party, colorful',
    suggestedCameraPreset: 'steady-cam, wide-ensemble',
  },
  {
    id: 'corrido-tumbado-original',
    nameEn: 'Corrido Tumbado Original',
    nameEs: 'Corrido Tumbado Original',
    descriptionEn: 'Modern trap-influenced corrido with poetic lyrics focus',
    descriptionEs: 'Corrido moderno influenciado por trap con enfoque en líricas poéticas',
    locale: ['es-MX', 'es-US'],
    genre: 'corrido tumbado',
    mood: 'introspective',
    bpmMin: 80,
    bpmMax: 95,
    defaultBpm: 88,
    key: 'Dm',
    instruments: ['strings', 'trumpet', 'synth', 'lofi-drums', 'bass'],
    styleTags: ['poetic', 'introspective', 'modern', 'trap-influence'],
    promptTemplateEn: 'Trap-corrido instrumental with soft strings, poetic trumpet, lo-fi drums, introspective vibe, modern storytelling',
    promptTemplateEs: 'Instrumental trap-corrido con cuerdas suaves, trompeta poética, batería lo-fi, vibra introspectiva, narrativa moderna',
    negativePrompt: 'fast tempo, aggressive, heavy metal, voice imitation, artist name',
    culturalNotes: 'Corrido tumbado blends traditional Mexican corrido with contemporary trap; emphasizes storytelling over regional stereotypes',
    suggestedVideoStyle: 'desert-landscape, introspective-portrait, story-narrative',
    suggestedCameraPreset: 'slow-pan, intimate-focus',
  },
  {
    id: 'regional-mexicano-original',
    nameEn: 'Regional Mexicano Original',
    nameEs: 'Regional Mexicano Original',
    descriptionEn: 'Contemporary regional Mexican with traditional instrumentation and modern arrangement',
    descriptionEs: 'Regional mexicano contemporáneo con instrumentación tradicional y arreglo moderno',
    locale: ['es-MX'],
    genre: 'regional mexicano',
    mood: 'warm',
    bpmMin: 85,
    bpmMax: 110,
    defaultBpm: 95,
    key: 'G',
    instruments: ['trumpet', 'saxophone', 'accordion', 'trombone', 'percussion', 'bass'],
    styleTags: ['traditional', 'warm', 'celebratory', 'festive'],
    promptTemplateEn: 'Regional Mexican with bright brass section, accordion harmony, traditional rhythms, celebratory and warm production',
    promptTemplateEs: 'Regional mexicano con sección de metales brillantes, armonía de acordeón, ritmos tradicionales, producción celebratoria y cálida',
    negativePrompt: 'voice imitation, American country, rock fusion, lo-fi',
    culturalNotes: 'Regional Mexican includes banda, norteño, and other styles from Northern Mexico; rich in tradition but evolving with contemporary production',
    suggestedVideoStyle: 'festival, celebration, countryside, tradition-meets-modern',
    suggestedCameraPreset: 'ensemble-wide, celebratory-group',
  },
  {
    id: 'latin-trap',
    nameEn: 'Latin Trap',
    nameEs: 'Latin Trap',
    descriptionEn: 'Hard-hitting trap with Latin percussion and Spanish-language sensibility',
    descriptionEs: 'Trap contundente con percusión latina y sensibilidad del idioma español',
    locale: ['es-MX', 'es-CO', 'es-PR', 'es-US'],
    genre: 'latin trap',
    mood: 'intense',
    bpmMin: 80,
    bpmMax: 95,
    defaultBpm: 88,
    key: 'Cm',
    instruments: ['drums', 'bass', 'synth', 'percussion', 'strings'],
    styleTags: ['intense', 'urban', 'hard-hitting', 'modern'],
    promptTemplateEn: 'Latin trap with hard-hitting drums, sub-bass, Latin percussion elements, urban attitude, modern production',
    promptTemplateEs: 'Latin trap con batería contundente, sub-bass, elementos de percusión latina, actitud urbana, producción moderna',
    negativePrompt: 'soft strings, acoustic, voice imitation, artist reference',
    culturalNotes: 'Latin trap emerged from Puerto Rico and Colombia; blends Caribbean rhythms with trap production',
    suggestedVideoStyle: 'urban-street, dark-aesthetic, street-culture',
    suggestedCameraPreset: 'dynamic-cuts, high-contrast',
  },
  {
    id: 'afro-latin-electronic',
    nameEn: 'Afro-Latin Electronic',
    nameEs: 'Afro-Latino Electrónico',
    descriptionEn: 'Groovy electronic with Afro-Caribbean percussion and rhythms',
    descriptionEs: 'Electrónico groovy con percusión afrocaribeña y ritmos',
    locale: ['es-CO', 'es-PR', 'es-CU'],
    genre: 'electronic',
    mood: 'groovy',
    bpmMin: 100,
    bpmMax: 130,
    defaultBpm: 115,
    key: 'Fm',
    instruments: ['synth', 'percussion', 'bass', 'drums', 'strings'],
    styleTags: ['groovy', 'electronic', 'afro-caribbean', 'dance'],
    promptTemplateEn: 'Afro-Latin electronic with pulsing synths, layered Afro-Caribbean percussion, groovy bassline, hypnotic rhythm',
    promptTemplateEs: 'Afro-latino electrónico con sintetizadores pulsantes, percusión afrocaribeña en capas, línea de bajo groovy, ritmo hipnótico',
    negativePrompt: 'acoustic guitar, country, voice imitation',
    culturalNotes: 'Afro-Latin sounds derive from African diaspora rhythms preserved in Caribbean and Latin music traditions',
    suggestedVideoStyle: 'dance-club, vibrant-colors, group-celebration',
    suggestedCameraPreset: 'dynamic-rhythm, color-saturated',
  },
  {
    id: 'salsa-urbana',
    nameEn: 'Salsa Urbana',
    nameEs: 'Salsa Urbana',
    descriptionEn: 'Contemporary salsa with modern production and hip-hop influences',
    descriptionEs: 'Salsa contemporánea con producción moderna e influencias hip-hop',
    locale: ['es-PR', 'es-NY', 'es-US'],
    genre: 'salsa',
    mood: 'energetic',
    bpmMin: 160,
    bpmMax: 180,
    defaultBpm: 170,
    key: 'Cmin',
    instruments: ['horns', 'percussion', 'synth', 'bass', 'drums'],
    styleTags: ['energetic', 'urban', 'dance', 'modern'],
    promptTemplateEn: 'Contemporary urban salsa with modern synth arrangements, layered brass, hip-hop influenced drums, dance rhythm',
    promptTemplateEs: 'Salsa urbana contemporánea con arreglos de sintetizadores modernos, metales en capas, batería influenciada por hip-hop, ritmo de baile',
    negativePrompt: 'traditional acoustic, voice imitation, slow ballad',
    culturalNotes: 'Salsa originated in Puerto Rico and Cuba; urban salsa blends classical salsa with contemporary production and urban culture',
    suggestedVideoStyle: 'dance-floor, nightlife, street-dance',
    suggestedCameraPreset: 'rhythm-synced, dynamic-movement',
  },
  {
    id: 'bachata-pop',
    nameEn: 'Bachata Pop',
    nameEs: 'Bachata Pop',
    descriptionEn: 'Modern bachata with pop production and contemporary appeal',
    descriptionEs: 'Bachata moderna con producción pop y atractivo contemporáneo',
    locale: ['es-DO', 'es-CO', 'es-US'],
    genre: 'bachata',
    mood: 'romantic',
    bpmMin: 70,
    bpmMax: 90,
    defaultBpm: 80,
    key: 'F#m',
    instruments: ['strings', 'acoustic-guitar', 'synth', 'bass', 'percussion'],
    styleTags: ['romantic', 'smooth', 'modern', 'pop-forward'],
    promptTemplateEn: 'Modern bachata with romantic string arrangements, contemporary synth layers, smooth groove, pop-influenced production',
    promptTemplateEs: 'Bachata moderna con arreglos románticos de cuerdas, capas de sintetizadores contemporáneos, groove suave, producción influenciada por pop',
    negativePrompt: 'hard-rock, electronic-only, voice imitation, wedding cliché',
    culturalNotes: 'Bachata originated in Dominican Republic; traditionally romantic but now embraces diverse themes and modern production',
    suggestedVideoStyle: 'romantic-landscape, intimate-scene, sunset',
    suggestedCameraPreset: 'slow-romance, warm-lighting',
  },
  {
    id: 'andean-cinematic',
    nameEn: 'Andean Cinematic',
    nameEs: 'Andean Cinemático',
    descriptionEn: 'Cinematic orchestral with Andean pan-flute and traditional instruments',
    descriptionEs: 'Orquestal cinemático con flauta de pan andina e instrumentos tradicionales',
    locale: ['es-PE', 'es-BO', 'es-EC', 'es-CL'],
    genre: 'andean',
    mood: 'cinematic',
    bpmMin: 60,
    bpmMax: 85,
    defaultBpm: 72,
    key: 'Em',
    instruments: ['panflute', 'strings', 'percussion', 'bass', 'woodwinds'],
    styleTags: ['cinematic', 'traditional', 'peaceful', 'landscape'],
    promptTemplateEn: 'Cinematic Andean with traditional pan-flute melody, lush orchestral strings, peaceful rhythm, mountain landscape atmosphere',
    promptTemplateEs: 'Andean cinemático con melodía tradicional de flauta de pan, cuerdas orquestales exuberantes, ritmo pacífico, atmósfera de paisaje montañoso',
    negativePrompt: 'heavy drums, electronic-only, urban, voice imitation',
    culturalNotes: 'Andean music traditions preserve Indigenous musical heritage from Peru, Bolivia, Ecuador, and Chile; deeply connected to landscape and spirituality',
    suggestedVideoStyle: 'mountain-landscape, nature-documentary, spiritual-journey',
    suggestedCameraPreset: 'wide-vista, slow-contemplative',
  },
  {
    id: 'bossa-mpb-fusion',
    nameEn: 'Bossa / MPB Fusion',
    nameEs: 'Bossa / MPB Fusión',
    descriptionEn: 'Contemporary fusion of bossa nova and Brazilian popular music',
    descriptionEs: 'Fusión contemporánea de bossa nova y música popular brasileña',
    locale: ['pt-BR'],
    genre: 'bossa / mpb',
    mood: 'sophisticated',
    bpmMin: 90,
    bpmMax: 110,
    defaultBpm: 100,
    key: 'Cmaj7',
    instruments: ['acoustic-guitar', 'piano', 'bass', 'percussion', 'strings'],
    styleTags: ['sophisticated', 'jazz-influenced', 'smooth', 'brazilian'],
    promptTemplateEn: 'Contemporary bossa nova fusion with jazz harmonies, smooth acoustic guitar, subtle percussion, sophisticated vibe',
    promptTemplateEs: 'Fusión de bossa nova contemporánea con armonías de jazz, guitarra acústica suave, percusión sutil, vibra sofisticada',
    negativePrompt: 'aggressive, electronic-only, voice imitation, heavy drums',
    culturalNotes: 'Bossa nova and MPB are iconic Brazilian forms; bossa combines samba rhythm with jazz sophistication; MPB carries poetic and political traditions',
    suggestedVideoStyle: 'intimate-lounge, jazz-café, night-elegance',
    suggestedCameraPreset: 'warm-lighting, close-intimate',
  },
  {
    id: 'documentary-underscore',
    nameEn: 'Documentary Underscore',
    nameEs: 'Partitura Documental',
    descriptionEn: 'Cinematic underscore for documentary and educational content',
    descriptionEs: 'Partitura cinemática para contenido documental y educativo',
    locale: ['en-US', 'es-MX', 'es-CO'],
    genre: 'cinematic',
    mood: 'informative',
    bpmMin: 60,
    bpmMax: 90,
    defaultBpm: 70,
    key: 'Amin',
    instruments: ['strings', 'piano', 'woodwinds', 'subtle-percussion', 'bass'],
    styleTags: ['cinematic', 'documentary', 'educational', 'inspiring'],
    promptTemplateEn: 'Documentary underscore with lush orchestral strings, thoughtful piano, subtle woodwinds, inspiring yet grounded atmosphere',
    promptTemplateEs: 'Partitura documental con cuerdas orquestales exuberantes, piano reflexivo, vientos sutiles, atmósfera inspiradora pero fundamentada',
    negativePrompt: 'pop melody, voice singing, hard-hitting drums, commercial jingle',
    culturalNotes: 'Documentary music should support storytelling without dominating narrative; appeals to global audiences across LatAm documentaries',
    suggestedVideoStyle: 'documentary-nature, interview, research-footage',
    suggestedCameraPreset: 'steady-cam, educational-clarity',
  },
  {
    id: 'ngo-anthem',
    nameEn: 'NGO Campaign Anthem',
    nameEs: 'Himno de Campaña NGO',
    descriptionEn: 'Inspirational anthem for social impact campaigns',
    descriptionEs: 'Himno inspirador para campañas de impacto social',
    locale: ['es-MX', 'es-CO', 'es-AR', 'es-PE'],
    genre: 'cinematic',
    mood: 'inspiring',
    bpmMin: 90,
    bpmMax: 110,
    defaultBpm: 100,
    key: 'Gmaj',
    instruments: ['orchestral', 'choir-like-synth', 'percussion', 'bass', 'uplifting-synth'],
    styleTags: ['inspiring', 'social-impact', 'cinematic', 'uplifting'],
    promptTemplateEn: 'Inspirational campaign anthem with uplifting orchestration, hopeful melodic progression, driving rhythm, inclusive energy',
    promptTemplateEs: 'Himno inspirador de campaña con orquestación animadora, progresión melódica esperanzadora, ritmo impulsor, energía inclusiva',
    negativePrompt: 'dark tone, voice imitation, commercial jingle feel, sarcasm',
    culturalNotes: 'LatAm has strong social advocacy traditions; music should feel inclusive and empowering for diverse communities',
    suggestedVideoStyle: 'community-gathering, hope-narrative, diverse-portraits',
    suggestedCameraPreset: 'wide-collective, uplifting-movement',
  },
  {
    id: 'social-impact-score',
    nameEn: 'Social-Impact Cinematic Score',
    nameEs: 'Partitura Cinemática de Impacto Social',
    descriptionEn: 'Powerful cinematic score for social impact narratives',
    descriptionEs: 'Partitura cinemática poderosa para narrativas de impacto social',
    locale: ['es-MX', 'es-CO', 'es-AR', 'es-CL'],
    genre: 'cinematic',
    mood: 'powerful',
    bpmMin: 70,
    bpmMax: 95,
    defaultBpm: 80,
    key: 'Dmin',
    instruments: ['strings', 'brass', 'piano', 'percussion', 'bass'],
    styleTags: ['cinematic', 'powerful', 'emotional', 'impactful'],
    promptTemplateEn: 'Powerful cinematic score with emotional string swells, determined brass accents, grounded rhythm, profound impact',
    promptTemplateEs: 'Partitura cinemática poderosa con hinchazones de cuerdas emocionales, acentos de latón determinados, ritmo fundamentado, impacto profundo',
    negativePrompt: 'light-hearted, comedic, pop-commercial, voice imitation',
    culturalNotes: 'Social impact narratives are prominent in LatAm documentary and media; music should convey both struggle and hope',
    suggestedVideoStyle: 'change-narrative, personal-story, before-after',
    suggestedCameraPreset: 'dramatic-lighting, emotional-focus',
  },
  {
    id: 'brand-jingle',
    nameEn: 'Brand Jingle',
    nameEs: 'Jingle de Marca',
    descriptionEn: 'Catchy, memorable brand jingle for advertising',
    descriptionEs: 'Jingle pegadizo y memorable para publicidad de marca',
    locale: ['es-MX', 'es-CO', 'es-AR', 'en-US'],
    genre: 'commercial',
    mood: 'catchy',
    bpmMin: 100,
    bpmMax: 130,
    defaultBpm: 120,
    key: 'Cmaj',
    instruments: ['synth', 'drums', 'bass', 'bright-piano', 'percussion'],
    styleTags: ['catchy', 'memorable', 'upbeat', 'commercial'],
    promptTemplateEn: 'Catchy brand jingle with memorable melodic hook, upbeat rhythm, bright instrumentation, easy to remember',
    promptTemplateEs: 'Jingle de marca pegadizo con gancho melódico memorable, ritmo animado, instrumentación brillante, fácil de recordar',
    negativePrompt: 'slow, sad, heavy, voice imitation, artist name',
    culturalNotes: 'Brand messaging for LatAm should feel modern, inclusive, and avoid regional clichés',
    suggestedVideoStyle: 'product-showcase, lifestyle-moment, brand-identity',
    suggestedCameraPreset: 'bright-colors, quick-cuts',
  },
  {
    id: 'creator-intro',
    nameEn: 'Creator Intro Theme',
    nameEs: 'Tema de Introducción de Creador',
    descriptionEn: 'Signature intro theme for content creators (YouTube, TikTok, etc.)',
    descriptionEs: 'Tema de introducción distintivo para creadores de contenido',
    locale: ['es-MX', 'es-CO', 'es-US'],
    genre: 'electronic',
    mood: 'energetic',
    bpmMin: 120,
    bpmMax: 150,
    defaultBpm: 130,
    key: 'Em',
    instruments: ['synth', 'drums', 'bass', 'percussion', 'lead-synth'],
    styleTags: ['energetic', 'modern', 'catchy', 'digital-native'],
    promptTemplateEn: 'Energetic creator intro with punchy drums, modern synth lead, dynamic rhythm, instant recognition potential',
    promptTemplateEs: 'Introducción de creador energética con batería contundente, sintetizador melódico moderno, ritmo dinámico, potencial de reconocimiento instantáneo',
    negativePrompt: 'slow, acoustic, sad, voice imitation',
    culturalNotes: 'Creator culture is global; intro should feel modern and platform-agnostic',
    suggestedVideoStyle: 'creator-signature, fast-cuts, brand-identity',
    suggestedCameraPreset: 'dynamic-energy, quick-movement',
  },
  {
    id: 'music-video-hook',
    nameEn: 'Music Video Hook',
    nameEs: 'Gancho de Video Musical',
    descriptionEn: '15-30 second catchy hook for music video intros',
    descriptionEs: 'Gancho pegadizo de 15-30 segundos para intros de videos musicales',
    locale: ['es-MX', 'es-CO', 'es-PR', 'es-US'],
    genre: 'pop',
    mood: 'catchy',
    bpmMin: 100,
    bpmMax: 130,
    defaultBpm: 115,
    key: 'Gmaj',
    instruments: ['synth', 'drums', 'bass', 'strings', 'percussion'],
    styleTags: ['catchy', 'memorable', 'short-form', 'video-native'],
    promptTemplateEn: 'Catchy 30-second music video hook with instant melodic hook, driving rhythm, perfect for short-form video',
    promptTemplateEs: 'Gancho de video musical pegadizo de 30 segundos con gancho melódico instantáneo, ritmo impulsor, perfecto para video de corta duración',
    negativePrompt: 'slow build-up, long intro, voice imitation',
    culturalNotes: 'Short-form video culture is dominant in LatAm; hooks must grab attention immediately',
    suggestedVideoStyle: 'hook-visual, instant-impact, short-form',
    suggestedCameraPreset: 'dynamic-cuts, high-energy',
  },
  {
    id: 'telenovela-theme',
    nameEn: 'Telenovela Dramatic Theme',
    nameEs: 'Tema Dramático de Telenovela',
    descriptionEn: 'Over-the-top dramatic theme for telenovela and dramatic content',
    descriptionEs: 'Tema dramático exagerado para telenovela y contenido dramático',
    locale: ['es-MX', 'es-CO', 'es-AR'],
    genre: 'cinematic',
    mood: 'dramatic',
    bpmMin: 70,
    bpmMax: 95,
    defaultBpm: 80,
    key: 'Cmin',
    instruments: ['strings', 'dramatic-synth', 'piano', 'percussion', 'bass'],
    styleTags: ['dramatic', 'over-the-top', 'passionate', 'cinematic'],
    promptTemplateEn: 'Over-the-top dramatic telenovela theme with sweeping strings, passionate synth, intense rhythm, pure melodrama',
    promptTemplateEs: 'Tema dramático exagerado de telenovela con cuerdas amplias, sintetizador apasionado, ritmo intenso, melodrama puro',
    negativePrompt: 'light-hearted, comedic, minimal instrumentation, voice imitation',
    culturalNotes: 'Telenovela tradition is deeply rooted in LatAm culture; themes should embrace drama and emotion unapologetically',
    suggestedVideoStyle: 'dramatic-moment, passionate-encounter, tension-buildup',
    suggestedCameraPreset: 'slow-motion, emotional-close-up',
  },
  {
    id: 'street-documentary',
    nameEn: 'Street Documentary Score',
    nameEs: 'Partitura de Documental Callejero',
    descriptionEn: 'Authentic score for street culture and documentary narratives',
    descriptionEs: 'Partitura auténtica para cultura callejera y narrativas documentales',
    locale: ['es-MX', 'es-CO', 'es-AR', 'es-US'],
    genre: 'cinematic',
    mood: 'authentic',
    bpmMin: 80,
    bpmMax: 110,
    defaultBpm: 95,
    key: 'Gmin',
    instruments: ['percussion', 'strings', 'hip-hop-beats', 'bass', 'synth'],
    styleTags: ['authentic', 'urban', 'documentary', 'street-culture'],
    promptTemplateEn: 'Authentic street documentary score with urban percussion, subtle hip-hop beats, raw strings, grounded vibe',
    promptTemplateEs: 'Partitura documental callejera auténtica con percusión urbana, latidos hip-hop sutiles, cuerdas crudas, vibra fundamentada',
    negativePrompt: 'polished, commercial, voice imitation, heavy metal',
    culturalNotes: 'Street culture in LatAm is vibrant and diverse; music should feel authentic without appropriation',
    suggestedVideoStyle: 'street-life, real-people, urban-landscape',
    suggestedCameraPreset: 'documentary-realism, natural-lighting',
  },
  {
    id: 'festival-anthem',
    nameEn: 'Festival Campaign Anthem',
    nameEs: 'Himno de Campaña de Festival',
    descriptionEn: 'Celebratory anthem for music and cultural festivals',
    descriptionEs: 'Himno celebratorio para festivales musicales y culturales',
    locale: ['es-MX', 'es-CO', 'es-PE', 'es-AR'],
    genre: 'world',
    mood: 'celebratory',
    bpmMin: 100,
    bpmMax: 130,
    defaultBpm: 120,
    key: 'Gmaj',
    instruments: ['percussion', 'brass', 'strings', 'synth', 'drums'],
    styleTags: ['celebratory', 'festive', 'diverse', 'cultural'],
    promptTemplateEn: 'Celebratory festival anthem with diverse percussion, bright brass, joyful strings, inclusive party energy',
    promptTemplateEs: 'Himno de festival celebratorio con percusión diversa, metales brillantes, cuerdas alegres, energía inclusiva de fiesta',
    negativePrompt: 'dark, serious, voice imitation, slow tempo',
    culturalNotes: 'Festival music should celebrate cultural diversity and bring communities together',
    suggestedVideoStyle: 'festival-celebration, diverse-crowd, joyful-dancing',
    suggestedCameraPreset: 'wide-celebration, colorful-energy',
  },
];

/**
 * Get preset by ID
 * @param {string} id
 * @returns {object|null}
 */
export function getPresetById(id) {
  return LATAM_MUSIC_PRESETS.find(p => p.id === id) ?? null;
}

/**
 * Get all presets for a specific locale
 * @param {string} locale
 * @returns {object[]}
 */
export function getPresetsByLocale(locale) {
  return LATAM_MUSIC_PRESETS.filter(p => p.locale.includes(locale));
}

/**
 * Get presets by genre
 * @param {string} genre
 * @returns {object[]}
 */
export function getPresetsByGenre(genre) {
  return LATAM_MUSIC_PRESETS.filter(p => p.genre === genre);
}

/**
 * Get presets by mood
 * @param {string} mood
 * @returns {object[]}
 */
export function getPresetsByMood(mood) {
  return LATAM_MUSIC_PRESETS.filter(p => p.mood === mood);
}

/**
 * Convert preset to MusicGenerationRequest
 * @param {string} presetId
 * @param {object} overrides
 * @returns {object}
 */
export function presetToRequest(presetId, overrides = {}) {
  const preset = getPresetById(presetId);
  if (!preset) return null;

  const language = overrides.language ?? (preset.locale[0]?.startsWith('pt') ? 'pt' : preset.locale[0]?.startsWith('en') ? 'en' : 'es');
  const promptTemplate = language === 'es' ? preset.promptTemplateEs : (language === 'pt' ? preset.promptTemplateEs : preset.promptTemplateEn);

  return {
    mode: 'simple',
    title: overrides.title ?? preset.nameEn,
    prompt: overrides.prompt ?? promptTemplate,
    genre: preset.genre,
    mood: preset.mood,
    styleTags: preset.styleTags,
    bpm: overrides.bpm ?? preset.defaultBpm,
    key: overrides.key ?? preset.key,
    durationSeconds: overrides.durationSeconds ?? 60,
    language,
    locale: overrides.locale ?? preset.locale[0],
    instruments: preset.instruments,
    culturalStyle: 'LatAm',
    ...overrides,
  };
}
